spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:booking}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate.default_schema: ${DATABASE_SCHEMA:booking_schema}
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate.format_sql: ${HIBERNATE_FORMAT_SQL:false}

server:
  servlet:
    session:
      timeout: 30s

logging:
  level:
    root: ${SPRING_LOG_LEVEL:info}
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:info}
  file:
    name: logs/booking.log