spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: alessandro
    password: password
  jpa:
    properties:
      hibernate.default_schema: booking_schema
